In [152]:
import pandas as pd
import numpy as np
import sklearn
#importing packages


In [153]:
dataset = pd.read_csv("D:/ml datasets/pr/Marriage-status-Prediction-master/Marriage_training.csv")

In [154]:
dataset.head(10)

ID  GAGE  BAGE GP BP  AINCOME     STATUS
0   1    41    41  A  B   113764    Married
1   2    53    43  A  A   145963  Separated
2   3    47    37  A  B    42857   Divorced
3   4    47    44  B  A    95352    Married
4   5    21    59  B  B   182138  Separated
5   6    37    32  B  A    76006    Married
6   7    38    31  A  B    22874    Married
7   8    31    26  B  A   100729    Married
8   9    62    36  B  A    23875   Divorced
9  10    56    55  B  A   182209    Married

In [186]:
dataset=pd.DataFrame(dataset)
print("number of rows are "+str(len(data.axes[0])))
print("number of coulmns are "+str(len(data.axes[1])))

number of rows are 750
number of coulmns are 7


In [156]:
#preprocessing the data
#step 1
dataset=dataset.drop_duplicates()
#drop the duplicates

In [ ]:
#step 2 removing outliers
from scipy import stats

def drop_numerical_outliers(df, z_thresh=3):
    # Constrains will contain `True` or `False` depending on if it is a value below the threshold.
    constrains = df.select_dtypes(include=[np.number]) \
        .apply(lambda x: np.abs(stats.zscore(x)) < z_thresh, reduce=False) \
        .all(axis=1)
    # Drop (inplace) values set to be rejected
    df.drop(df.index[~constrains], inplace=True)

In [157]:
#step 3
dataset=dataset.dropna()
#drop the rows which are not assigned(empty)

In [158]:
#step 4
from sklearn.preprocessing import LabelEncoder
Lab = LabelEncoder()
dataset['GP']= Lab.fit_transform(dataset['GP'])
dataset['BP']= Lab.fit_transform(dataset['BP'])
dataset.head()

ID  GAGE  BAGE  GP  BP  AINCOME     STATUS
0   1    41    41   0   1   113764    Married
1   2    53    43   0   0   145963  Separated
2   3    47    37   0   1    42857   Divorced
3   4    47    44   1   0    95352    Married
4   5    21    59   1   1   182138  Separated

In [188]:
###### decide which type of learning we should use ############
     # if we observe the data has class label (STATUS) so we go should for supervised learning(It is like learning with a teacher)

In [159]:
dataset['STATUS']= Lab.fit_transform(dataset['STATUS'])


In [160]:
dataset.head()

ID  GAGE  BAGE  GP  BP  AINCOME  STATUS
0   1    41    41   0   1   113764       1
1   2    53    43   0   0   145963       2
2   3    47    37   0   1    42857       0
3   4    47    44   1   0    95352       1
4   5    21    59   1   1   182138       2

In [161]:
y=dataset.STATUS
x=dataset.drop(["STATUS","ID"],axis="columns")
#having id is of no use ,so we are removing it from our dataframe
#since status is our target variable we are removing from input data
#removing target attribute from inputs


In [162]:
x.head()

GAGE  BAGE  GP  BP  AINCOME
0    41    41   0   1   113764
1    53    43   0   0   145963
2    47    37   0   1    42857
3    47    44   1   0    95352
4    21    59   1   1   182138

In [163]:
y.head()

0    1
1    2
2    0
3    1
4    2
Name: STATUS, dtype: int32

In [164]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.25)
#here we are spliting our data in to train and test data
#traindata=75% of data
#testdata=25% of data
#the main reason we split the data in to test and train is we use train data to  build the model and we test data to check the accuracy of our model.

In [165]:
######  BUILDING NAIVE BAYES CLASSIFIER #######


from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(X_train, Y_train) 
  
# making predictions on the testing set 
Y_pred = gnb.predict(X_test) 

In [166]:
y_pred

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 1, 2, 2, 0, 1, 2, 0, 0,
       1, 1, 2, 1, 1, 0, 2, 1, 0, 0, 2, 0, 2, 2, 2, 1, 2, 2, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 0, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2,
       2, 2, 2, 1, 2, 2, 1, 1, 0, 0, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       0, 2, 2, 2, 1, 2, 2, 0, 2, 1, 0, 0, 2, 1, 2, 2, 1, 0, 2, 0, 1, 0,
       2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 1, 2, 0, 2, 2, 0, 1,
       2, 1, 0, 2, 2, 2, 0, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 0, 1, 1, 1, 2,
       2, 1, 1, 1, 2, 0, 2, 2, 0, 2, 0, 1, 2, 2, 2, 1, 2, 2, 1, 1, 2, 0,
       0, 0, 1, 2, 0, 2, 2, 0, 2, 0, 2, 2])

In [167]:
from sklearn.metrics import confusion_matrix

confusion_matrix(Y_pred,Y_test)

#The number of correct and incorrect predictions are summarized with count values and broken down by each class is given by confusion matrix

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [34, 62, 92]], dtype=int64)

In [168]:
from sklearn.metrics import accuracy_score

naivebayesscore=accuracy_score(Y_test,Y_pred)

#accuracy is the fraction of predictions our model got right.

print("accuracy of naivebayesscore model is ")
naivebayesscore

accuracy of naivebayesscore model is 


0.48936170212765956

In [169]:
############ BUILDING DECISION TREE CLASSIFIER ###############
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [170]:
Y_pred = dt.predict(X_test)
Y_pred

array([2, 1, 2, 2, 2, 2, 2, 2, 0, 2, 1, 0, 2, 2, 1, 1, 0, 2, 2, 0, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 0, 1, 1, 2, 2, 2, 0, 2, 1, 1, 1, 2, 0, 2, 1, 1, 1,
       2, 0, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2,
       1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2, 1, 0, 1, 2, 2, 0, 2, 0,
       2, 1, 1, 1, 1, 0, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 1, 1, 2, 0, 1, 1, 0, 2, 1, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 0, 0, 1, 1, 0, 2, 2, 2, 1, 1, 2, 0, 1, 2, 2,
       1, 0, 1, 0, 2, 1, 2, 1, 2, 1, 0, 2])

In [171]:
print ("confusion matrix for decision tree model")
confusion_matrix(Y_pred,Y_test)

confusion matrix for decision tree model


array([[16,  4,  8],
       [ 5, 30, 24],
       [13, 28, 60]], dtype=int64)

In [172]:
decisiontreescore=accuracy_score(Y_test,Y_pred)
print("accuracy of  model using decison tree is ")
decisiontreescore

accuracy of  model using decison tree is 


0.5638297872340425

In [173]:
##### BUILDING A MODEL USING KNN ##############



from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [174]:
Y_pred = classifier.predict(X_test)
print ("confusion matrix for decision tree model")
confusion_matrix(Y_pred,Y_test)

confusion matrix for decision tree model


array([[ 7,  7, 18],
       [12, 15, 31],
       [15, 40, 43]], dtype=int64)

In [175]:
KnnScore=accuracy_score(Y_test,Y_pred)
print("accuracy of  model using KNN is ")
KnnScore

accuracy of  model using KNN is 


0.34574468085106386

In [176]:
 ######## BUILDING A MODEL USING RANDOMFORESTCLASSIFIER #################




from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=200,random_state=0)
model.fit(X_train,Y_train)
#building the model

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [177]:
Y_predict=model.predict(X_test)
Y_predict
#predicting by giving test data as input

array([2, 2, 2, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 0, 2, 1, 1, 1, 2,
       2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1,
       2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1,
       2, 0, 1, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2, 2, 1, 2, 1, 2, 2, 1, 0, 2,
       2, 0, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1,
       2, 1, 1, 1, 1, 0, 1, 0, 2, 2, 2, 1, 2, 2, 2, 1, 1, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 1, 2, 0, 2, 2, 1, 2, 2, 1, 1, 0, 1, 1, 1, 0, 2,
       2, 0, 2, 2, 2, 2, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2,
       2, 0, 2, 2, 1, 2, 1, 1, 2, 1, 0, 1])

In [178]:

confusion_matrix(Y_predict,Y_test)
#confusion matrix

array([[26,  1,  0],
       [ 8, 60,  0],
       [ 0,  1, 92]], dtype=int64)

In [179]:

randomforestscore=accuracy_score(Y_test,Y_predict)

print("accuracy of randomforest model is") 
randomforestscore
#checking the accuracy of our model

accuracy of randomforest model is


0.9468085106382979

In [180]:
######################SUMMARY ######################
print("accuracy of naivebayesscore model is ",naivebayesscore)

print("accuracy of  model using decison tree is ",decisiontreescore)


print("accuracy of  model using KNN is ",KnnScore)


print("accuracy of randomforest model is",randomforestscore) 


#note :we bulid many models but randomforest gave us best so we can deploy in our application

accuracy of naivebayesscore model is  0.48936170212765956
accuracy of  model using decison tree is  0.5638297872340425
accuracy of  model using KNN is  0.34574468085106386
accuracy of randomforest model is 0.9468085106382979


In [151]:
#we observe that model bulit using knn algorithm is least accurate
#we observe that model build using random forest algorithm is more accurate than remaining models



####### REASON WHY RANDOM FOREST MODEL GOT HIGHER ACCURACY ##########
# 1) firstly ,it is an ensemble learning
# 2)It takes average of all decision trees of which it has built
# 3)It has got certain implict methods which removes all the outliers and all the noisy data
# 4)And if we observe the computational time taken by the model is also very less because all the decisions trees will be grown in parallel.
